apiVersion: v2
name: todo
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: "1.16.0"
dependencies:
  - name: backend
    version: "0.1.0"
    repository: "file://charts/backend"
