apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8880
  selector:
    app: todo-backend
